### ISSUE TITLE
Update to UE 5

### ISSUE THREAD

**Issue by CaioLima7** [npruehs/UnrealDI#9]

**Comment by CaioLima7** [comment]
Hello teams, thanks for plugin and create the possibility to Dependency Injection in UE. Plese update to UE 5
Thank you!

**Comment by npruehs** [comment]
Hey @CaioLima7 ! Unfortunately, the presented solution doesn't seem to survive a packaged build, because it's relying on meta tags. That's why I ceased work on this one, at least for the moment.

**Comment by CaioLima7** [comment]
Wow i understand, thank you!!
